### ISSUE TITLE
SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by seia-soto** [seia-soto/Serium#47]
2018-08-03T14:51:41.547021+00:00 app[worker.1]: Starting up at Fri Aug 03 2018 14:51:41 GMT+0000 (UTC)
2018-08-03T14:51:42.020195+00:00 app[worker.1]: /app/plugins/functions/translate/index.js:8
2018-08-03T14:51:42.020232+00:00 app[worker.1]:         description: '**' + res.from.language.iso ' to ' + nt.parameters[0] + '**\n\n' + res.text
2018-08-03T14:51:42.020234+00:00 app[worker.1]:                                                   ^^^^^^
2018-08-03T14:51:42.020237+00:00 app[worker.1]: 
2018-08-03T14:51:42.020239+00:00 app[worker.1]: SyntaxError: Unexpected string
2018-08-03T14:51:42.020241+00:00 app[worker.1]:     at createScript (vm.js:80:10)
2018-08-03T14:51:42.020243+00:00 app[worker.1]:     at Object.runInThisContext (vm.js:139:10)
2018-08-03T14:51:42.020244+00:00 app[worker.1]:     at Module._compile (module.js:616:28)
2018-08-03T14:51:42.020246+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:663:10)
2018-08-03T14:51:42.020248+00:00 app[worker.1]:     at Module.load (module.js:565:32)
2018-08-03T14:51:42.020249+00:00 app[worker.1]:     at tryModuleLoad (module.js:505:12)
2018-08-03T14:51:42.020251+00:00 app[worker.1]:     at Function.Module._load (module.js:497:3)
2018-08-03T14:51:42.020252+00:00 app[worker.1]:     at Module.require (module.js:596:17)
2018-08-03T14:51:42.020254+00:00 app[worker.1]:     at require (internal/module.js:11:18)
2018-08-03T14:51:42.020256+00:00 app[worker.1]:     at Object.<anonymous> (/app/plugins/index.js:35:19)

**Comment by seia-soto** [comment]
Fixed
