### ISSUE TITLE
TypeError: {(intermediate value)}.then is not a function

### ISSUE THREAD

**Issue by seia-soto** [seia-soto/Serium#48]
2018-08-03T14:56:14.899614+00:00 app[worker.1]: 
2018-08-03T14:56:14.899616+00:00 app[worker.1]: TypeError: {(intermediate value)}.then is not a function
2018-08-03T14:56:14.899619+00:00 app[worker.1]:     at Object.module.exports [as worker] (/app/plugins/functions/translate/index.js:4:56)
2018-08-03T14:56:14.899621+00:00 app[worker.1]:     at Client.client.on (/app/index.js:58:10)
2018-08-03T14:56:14.899623+00:00 app[worker.1]:     at emitOne (events.js:116:13)
2018-08-03T14:56:14.899625+00:00 app[worker.1]:     at Client.emit (events.js:211:7)
2018-08-03T14:56:14.899628+00:00 app[worker.1]:     at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
2018-08-03T14:56:14.899631+00:00 app[worker.1]:     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
2018-08-03T14:56:14.899633+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2018-08-03T14:56:14.899635+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2018-08-03T14:56:14.899637+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2018-08-03T14:56:14.899639+00:00 app[worker.1]:     at emitOne (events.js:116:13)
2018-08-03T14:56:15.005571+00:00 heroku[worker.1]: Process exited with status 1
2018-08-03T14:56:15.438464+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by seia-soto** [comment]
Fixed
